name: CI


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build